spring:
  application:
    name: sb13-monu-team01
  mongodb:
    representation:
      uuid: standard

  batch:
    job:
      enabled: false

logging:
  file:
    path: ${LOG_FILE_PATH:logs}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics

aws:
  s3:
    region: ${AWS_REGION:ap-northeast-2}

naver:
  api:
    client-id: ${NAVER_CLIENT_ID:test-client-id}
    client-secret: ${NAVER_CLIENT_SECRET:test-client-secret}
